// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — Neon's pooled
    // connection (pgbouncer) doesn't support the advisory locks Migrate uses.
    url: process.env["POSTGRES_URL_NON_POOLING"],
  },
});
